
server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
jwt:
  secret: "${JWT_SECRET}"

firebase:
  service-account-key-path: "${FIREBASE_SERVICE_ACCOUNT_KEY_PATH}"

webhook:
  secret: ${WEBHOOK_SECRET}

services:
  auth:
    base-url: ${AUTH_SERVICE_BASE_URL}